package com.sab.carm.fcm.security;

import com.sab.carm.fcm.audit.AuditEvent;
import com.sab.carm.fcm.audit.AuditService;
import javax.servlet.http.HttpServletRequest;
import org.slf4j.MDC;
import org.springframework.context.event.EventListener;
import org.springframework.security.authentication.event.AbstractAuthenticationFailureEvent;
import org.springframework.security.authentication.event.AuthenticationSuccessEvent;
import org.springframework.stereotype.Component;

/**
 * Audits Spring Security authentication events.
 *
 * This listener captures authentication events generated by
 * Spring Security itself, including failures that may occur
 * before application-level authentication handling completes.
 *
 * It does not perform authentication or authorization.
 */
@Component
public class SecurityAuditEventListener {

    private static final String UNKNOWN_USER = "unknown";

    private final AuditService auditService;
    private final HttpServletRequest request;

    public SecurityAuditEventListener(
            AuditService auditService,
            HttpServletRequest request) {

        this.auditService = auditService;
        this.request = request;
    }

    @EventListener
    public void onSuccess(
            AuthenticationSuccessEvent event) {

        String username =
                event.getAuthentication().getName();

        auditService.record(
                AuditEvent.loginSuccess(
                        username,
                        resolveRole(event.getAuthentication()),
                        resolveClientIp(),
                        MDC.get("correlationId")));
    }

    @EventListener
    public void onFailure(
            AbstractAuthenticationFailureEvent event) {

        String username =
                resolveUsername(event);

        String reason =
                event.getException() == null
                        ? "AUTHENTICATION_FAILED"
                        : event.getException()
                        .getClass()
                        .getSimpleName();

        auditService.record(
                AuditEvent.loginFailure(
                        username,
                        resolveClientIp(),
                        MDC.get("correlationId"),
                        reason));
    }

    private String resolveUsername(
            AbstractAuthenticationFailureEvent event) {

        if (event.getAuthentication() == null) {
            return UNKNOWN_USER;
        }

        String username =
                event.getAuthentication().getName();

        return username == null
                || username.trim().isEmpty()
                ? UNKNOWN_USER
                : username;
    }

    private String resolveRole(
            org.springframework.security.core.Authentication authentication) {

        if (authentication == null
                || authentication.getAuthorities() == null) {
            return null;
        }

        return authentication.getAuthorities()
                .stream()
                .map(authority ->
                        authority.getAuthority())
                .filter(authority ->
                        authority.startsWith("ROLE_"))
                .map(authority ->
                        authority.substring("ROLE_".length()))
                .findFirst()
                .orElse(null);
    }

    private String resolveClientIp() {

        String forwardedFor =
                request.getHeader("X-Forwarded-For");

        if (forwardedFor != null
                && !forwardedFor.trim().isEmpty()) {

            return forwardedFor
                    .split(",")[0]
                    .trim();
        }

        return request.getRemoteAddr();
    }
}